// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaQXkMEr9jJKmtoC-_yZ4eixATHdTpBhI',
    appId: '1:323504681870:web:4637bebd554c92801aeadf',
    messagingSenderId: '323504681870',
    projectId: 'esp826-test',
    authDomain: 'esp826-test.firebaseapp.com',
    databaseURL: 'https://esp826-test-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'esp826-test.firebasestorage.app',
    measurementId: 'G-5MBWM90XBV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHTrrnsLeqe2f3h4raT7P-a-veHHDg3u4',
    appId: '1:323504681870:android:12f01596c3a9b6861aeadf',
    messagingSenderId: '323504681870',
    projectId: 'esp826-test',
    databaseURL: 'https://esp826-test-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'esp826-test.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC07G0jBw7brh1OvT1f0Jrr16EyxuINXkA',
    appId: '1:323504681870:web:1f9113f3f3c1a64a1aeadf',
    messagingSenderId: '323504681870',
    projectId: 'esp826-test',
    authDomain: 'esp826-test.firebaseapp.com',
    databaseURL: 'https://esp826-test-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'esp826-test.firebasestorage.app',
    measurementId: 'G-01KGQRK2P0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZLEk61-oezobUDjMtXdEm1e-0BtZyGuI',
    appId: '1:323504681870:ios:54a018f62a87781d1aeadf',
    messagingSenderId: '323504681870',
    projectId: 'esp826-test',
    databaseURL: 'https://esp826-test-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'esp826-test.firebasestorage.app',
    iosBundleId: 'com.example.manegaManeuvergadjahmada',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZLEk61-oezobUDjMtXdEm1e-0BtZyGuI',
    appId: '1:323504681870:ios:54a018f62a87781d1aeadf',
    messagingSenderId: '323504681870',
    projectId: 'esp826-test',
    databaseURL: 'https://esp826-test-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'esp826-test.firebasestorage.app',
    iosBundleId: 'com.example.manegaManeuvergadjahmada',
  );

}